### ISSUE TITLE
[Bug] Miliastra Wonderland Ode Log cannot be imported due to JSON Structure Error

### ISSUE THREAD

**Issue by studiobutter** [Scighost/Starward#1633]
### Checklist

- [x] My issue was not mentioned by others, and it is not a duplicate issue.

### Description

With v0.15.7, the new MW Ode Logs doesn't work. Returning with JSON Exception Error

### Reproduction Steps

- Open MW Banner Log
- Click Update Records

### Expected Behavior

Records should be updated, Table should contain 15+ pulls for each banners

### Starward Version

v0.15.7

### Windows Version

26200.7019

### Log

[Starward_251101.log](https://github.com/user-attachments/files/23267616/Starward_251101.log)

### Additional Context

Off Topic Information:
- Incase Outfit Image Data isn't available, you can check out [harushin-py](https://github.com/seriaati/hakushin-py) on how to implement Outfit Image Data. You can check the main website [here](https://gi20.hakush.in/beyond)
- For exporting Logs, UIGF Team is already working on an update for the UIGF Standard which you can check out here [UIGF-org.github.io/#108](https://github.com/UIGF-org/UIGF-org.github.io/issues/108). You can implement them later down the line

**Comment by studiobutter** [comment]
The screenshot is somehow lost during upload, here's the screenshot again:

<img width="1186" height="669" alt="Image" src="https://github.com/user-attachments/assets/c0044721-679c-48ca-8303-48ae09619f83" />

**Comment by DarkAssassin48** [comment]
++

**Comment by Scighost** [comment]
Can you provide the web cache file `data_2`? Click this button and upload the file in explorer.

<img width="232" height="218" alt="Image" src="https://github.com/user-attachments/assets/3a21e16e-ca48-48d3-9391-f9a35e89c67f" />

**Comment by DarkAssassin48** [comment]
[data_2.zip](https://github.com/user-attachments/files/23280665/data_2.zip)

**Comment by Scighost** [comment]
Fixed. Before publish, you can find the full URL in file `data_2` starting with:
```
https://public-operation-hk4e-sg.hoyoverse.com/gacha_info/api/getBeyondGachaLog?
```

And the use Input URL to get records.

<img width="128" height="122" alt="Image" src="https://github.com/user-attachments/assets/49314ff2-d5c3-4e95-b9fa-4982f1597c6a" />

**Comment by smallg0at** [comment]
我也有此问题（国服）。手动找URL并不能解决此问题。

<img width="1244" height="394" alt="Image" src="https://github.com/user-attachments/assets/8b4ed179-fa07-4c69-bf67-192f0970dae4" />

```
[17:59:35.882] [INFO] [Starward.exe (36068)] Starward.Features.Gacha.GenshinBeyondGachaService
Last gacha log id of uid <redacted> is 0

[17:59:36.404] [EROR] [Starward.exe (36068)] Starward.Features.Gacha.GenshinBeyondGachaPage
Update gacha log
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.list[0].rank_type | LineNumber: 0 | BytePositionInLine: 203.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.ThrowHelper.ThrowFormatException(NumericType numericType)
   at System.Text.Json.Serialization.Converters.Int32Converter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient client, Task`1 responseTask, Boolean usingResponseHeadersRead, CancellationTokenSource linkedCTS, Func`4 deserializeMethod, TJsonOptions jsonOptions, CancellationToken cancellationToken)
   at Starward.Core.Gacha.Genshin.GenshinBeyondGachaClient.GetGachaLogByQueryAsync(String gachaUrlPrefix, BeyondGachaLogQuery param, CancellationToken cancellationToken) in C:\Users\me\OneDrive\Code\Starward\src\Starward.Core\Gacha\Genshin\GenshinBeyondGachaClient.cs:line 124
   at Starward.Core.Gacha.Genshin.GenshinBeyondGachaClient.GetGachaLogByTypeAsync(String prefix, Int32 gachaType, Int64 endId, IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\me\OneDrive\Code\Starward\src\Starward.Core\Gacha\Genshin\GenshinBeyondGachaClient.cs:line 58
   at Starward.Core.Gacha.Genshin.GenshinBeyondGachaClient.GetGachaLogAsync(String gachaUrl, Int64 endId, String lang, IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\me\OneDrive\Code\Starward\src\Starward.Core\Gacha\Genshin\GenshinBeyondGachaClient.cs:line 44
   at Starward.Features.Gacha.GenshinBeyondGachaService.GetGachaLogAsync(String url, Boolean all, String lang, IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\me\OneDrive\Code\Starward\src\Starward\Features\Gacha\GenshinBeyondGachaService.cs:line 112
   at Starward.Features.Gacha.GenshinBeyondGachaPage.UpdateGachaLogInternalAsync(String url, Boolean all) in C:\Users\me\OneDrive\Code\Starward\src\Starward\Features\Gacha\GenshinBeyondGachaPage.xaml.cs:line 224
   at Starward.Features.Gacha.GenshinBeyondGachaPage.UpdateGachaLogAsync(String param) in C:\Users\me\OneDrive\Code\Starward\src\Starward\Features\Gacha\GenshinBeyondGachaPage.xaml.cs:line 186
```

**Comment by DarkAssassin48** [comment]
<img width="1186" height="669" alt="Image" src="https://github.com/user-attachments/assets/0c47b1d3-2bd9-4bd5-a99f-3e386cd3e676" />
In v0.15.8, the error still occurs.

[Starward_251104.log](https://github.com/user-attachments/files/23329092/Starward_251104.log)
